### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by rcass** [mountainManCode/aloha-project-1#1]
Can't remember if I mentioned this, but be sure to add a README.md before submitting your project!

**Comment by rcass** [comment]
I noticed you have done this, so I will close the issue! Which is something you can also do once you resolve the ticket!

It is very satisfying to close issue tickets and alerts the original poster that it is resolved! 👍

**Comment by mountainManCode** [comment]
Aw, I was unaware I could close anything. I will definitely do it next
time.  :)
